### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([46, 82, 56, 84, 98, 62, 28, 37,  9, 32, 71, 72, 70, 15, 83])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[23, 45,  8, 15],
       [76, 90, 30, 26],
       [48, 41, 82, 73],
       [49, 57, 96, 67],
       [67, 44, 25, 38],
       [25, 34, 89,  8]])

In [3]:
np.sort(a)[::-1]#descending order

array([98, 83, 82, 82, 80, 66, 56, 44, 43, 31, 28, 26, 19, 18,  1])

In [ ]:
np.sort(b,axis=0)

array([[ 8, 18,  2,  6],
       [12, 52, 31,  7],
       [29, 63, 42,  9],
       [38, 71, 44, 55],
       [40, 87, 47, 72],
       [61, 93, 83, 85]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
# code
np.append(a,200)

array([ 11,  53,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21, 200])

In [33]:
b.shape[0]

6

In [32]:
np.append(b,np.ones((b.shape[0],1)),axis=1) #

array([[96., 65., 86., 24.,  1.],
       [66., 88., 77., 73.,  1.],
       [86., 84., 11., 15.,  1.],
       [24., 28., 95., 48.,  1.],
       [19., 56.,  3.,  2.,  1.],
       [57., 61., 78., 39.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [4]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [39]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [43]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [42]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [45]:
# code
a

array([28, 18, 19, 82, 44, 66, 31, 80, 43, 98, 26, 82, 56, 83,  1])

In [46]:
a.shape

(15,)

In [49]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [51]:
np.expand_dims(a,axis=1)

array([[28],
       [18],
       [19],
       [82],
       [44],
       [66],
       [31],
       [80],
       [43],
       [98],
       [26],
       [82],
       [56],
       [83],
       [ 1]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [52]:
# find all indices with value greater than 50
# np.where(condition,if true, if false)
np.where(a>50)

(array([ 3,  5,  7,  9, 11, 12, 13]),)

In [56]:
# replace all values > 50 with 0
np.where(a>50,0,a
         )

array([28, 18, 19,  0, 44,  0, 31,  0, 43,  0, 26,  0,  0,  0,  1])

In [ ]:
np.where(a%2 == 0,0,a)

array([11, 53,  0,  0,  0, 37,  0,  0,  5,  0,  0,  9,  0,  0, 21])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.argmax(a)

6

In [ ]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [ ]:
np.argmax(b,axis=0)

array([2, 2, 2, 3])

In [ ]:
np.argmax(b,axis=1)

array([1, 3, 1, 3, 1, 1])

In [ ]:
# np.argmin
np.argmin(a)

13

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [5]:
a

array([46, 82, 56, 84, 98, 62, 28, 37,  9, 32, 71, 72, 70, 15, 83])

In [6]:
np.cumsum(a)

array([ 46, 128, 184, 268, 366, 428, 456, 493, 502, 534, 605, 677, 747,
       762, 845])

In [7]:
b

array([[23, 45,  8, 15],
       [76, 90, 30, 26],
       [48, 41, 82, 73],
       [49, 57, 96, 67],
       [67, 44, 25, 38],
       [25, 34, 89,  8]])

In [8]:
np.cumsum(b,axis=1)

array([[ 23,  68,  76,  91],
       [ 76, 166, 196, 222],
       [ 48,  89, 171, 244],
       [ 49, 106, 202, 269],
       [ 67, 111, 136, 174],
       [ 25,  59, 148, 156]])

In [11]:
np.cumsum(b)

array([  23,   68,   76,   91,  167,  257,  287,  313,  361,  402,  484,
        557,  606,  663,  759,  826,  893,  937,  962, 1000, 1025, 1059,
       1148, 1156])

In [10]:
# np.cumprod
np.cumprod(a)

array([                  46,                 3772,               211232,
                   17743488,           1738861824,         107809433088,
              3018664126464,      111690572679168,     1005215154112512,
          32166884931600384,  2283848830143627264, -1583580893044801536,
        -170198070878797824, -2552971063181967360, -8982413433298223104])

In [9]:
a

array([46, 82, 56, 84, 98, 62, 28, 37,  9, 32, 71, 72, 70, 15, 83])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [12]:
a

array([46, 82, 56, 84, 98, 62, 28, 37,  9, 32, 71, 72, 70, 15, 83])

In [13]:
np.percentile(a,50)

62.0

In [ ]:
np.median(a)

37.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [14]:
# code
a

array([46, 82, 56, 84, 98, 62, 28, 37,  9, 32, 71, 72, 70, 15, 83])

In [15]:
np.histogram(a,bins=[0,50,100]) #(array,binsize)

(array([6, 9]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [16]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [20]:
# code
a


array([46, 82, 56, 84, 98, 62, 28, 37,  9, 32, 71, 72, 70, 15, 83])

In [25]:
items = [10,20,30,40,50,60,70,80,90,100]

np.isin(a,items) #searches for the items of list in the array

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False])

In [26]:
a[np.isin(a,items)]

array([70])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [27]:
# code
a

array([46, 82, 56, 84, 98, 62, 28, 37,  9, 32, 71, 72, 70, 15, 83])

In [28]:
np.flip(a)

array([83, 15, 70, 72, 71, 32,  9, 37, 28, 62, 98, 84, 56, 82, 46])

In [29]:
b

array([[23, 45,  8, 15],
       [76, 90, 30, 26],
       [48, 41, 82, 73],
       [49, 57, 96, 67],
       [67, 44, 25, 38],
       [25, 34, 89,  8]])

In [30]:
np.flip(b,axis=1)

array([[15,  8, 45, 23],
       [26, 30, 90, 76],
       [73, 82, 41, 48],
       [67, 96, 57, 49],
       [38, 25, 44, 67],
       [ 8, 89, 34, 25]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [31]:
# code
a

array([46, 82, 56, 84, 98, 62, 28, 37,  9, 32, 71, 72, 70, 15, 83])

In [32]:
np.put(a,[0,1],[110,530])

In [33]:
a

array([110, 530,  56,  84,  98,  62,  28,  37,   9,  32,  71,  72,  70,
        15,  83])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [ ]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [ ]:
np.delete(a,[0,2,4])

array([530,  50,  37,  94,  92,   5,  30,  68,   9,  78,   2,  21])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [34]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(n,m)

array([6, 7])

In [ ]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [35]:
np.in1d(m,1)

array([ True, False, False, False, False])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [37]:
# code
a

array([110, 530,  56,  84,  98,  62,  28,  37,   9,  32,  71,  72,  70,
        15,  83])

In [40]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 56, 75, 75, 62, 28, 37, 25, 32, 71, 72, 70, 25, 75])